### ISSUE TITLE
missing eina dependency

### ISSUE THREAD

**Issue by zmike** [marcelhollerbach/efl-utility#1]
[1/2] Compiling C object 'efl-check@exe/checks.c.o'.
FAILED: efl-check@exe/checks.c.o 
ccache gcc -Iefl-check@exe -I. -I.. -I/usr/include/efl-1 -I/usr/include/eolian-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -O0 -g -Wall -Wextra -Wshadow  -MD -MQ 'efl-check@exe/checks.c.o' -MF 'efl-check@exe/checks.c.o.d' -o 'efl-check@exe/checks.c.o' -c ../checks.c
In file included from ../checks.c:4:
/usr/include/eolian-1/Eolian.h:34:10: fatal error: Eina.h: No such file or directory
 #include <Eina.h>
          ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by marcelhollerbach** [comment]
Well, eina is a dependency of eolian, why is it not taken into account for you ? I meanwhile just added eina to the dependency list, can you check it works now ?

**Comment by zmike** [comment]
Yea it works now
